/**
 *
 * This class is a JPanel GUI that allows the user
 * to input their name and the number of opponents.
 * 
 */
public class GameStart extends javax.swing.JPanel {

    /**
     * Creates new form GameStart
     */
    public GameStart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        _startGame = new javax.swing.JButton();
        _titleLabel = new javax.swing.JLabel();
        _nameLabel = new javax.swing.JLabel();
        _numOppLabel = new javax.swing.JLabel();
        _name = new javax.swing.JTextField();
        _numOpp = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(71, 113, 72));

        _startGame.setText("Start Game");
        _startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _startGameActionPerformed(evt);
            }
        });

        _titleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        _titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        _titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _titleLabel.setText("Welcome to Pocket Rockets Poker!");

        _nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        _nameLabel.setText("Name:");

        _numOppLabel.setForeground(new java.awt.Color(255, 255, 255));
        _numOppLabel.setText("Number of Opponents:");

        _name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _nameActionPerformed(evt);
            }
        });

        _numOpp.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] { 1, 2, 3, 4, 5, 6, 7 }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(_numOppLabel)
                            .addGap(45, 45, 45)
                            .addComponent(_numOpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(_nameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_name, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(_startGame)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(_titleLabel)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(_titleLabel)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_nameLabel)
                    .addComponent(_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_numOppLabel)
                    .addComponent(_numOpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(_startGame)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void _nameActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void _startGameActionPerformed(java.awt.event.ActionEvent evt) {                                           
        //TODO add error handling for user input... (RegExp name)
        String name = _name.getText();
        int numOpponenets = (int) _numOpp.getSelectedItem();
        
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.JTextField _name;
    private javax.swing.JLabel _nameLabel;
    private javax.swing.JComboBox<Integer> _numOpp;
    private javax.swing.JLabel _numOppLabel;
    private javax.swing.JButton _startGame;
    private javax.swing.JLabel _titleLabel;
    // End of variables declaration                   
}
